import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenu from "@/components/nav_menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menu = [
    { name: "Personas", path: "/personas" },
    { name: "Medicamentos", path: "/medicamentos" },
    { name: "Recetas", path: "/recetas" },
  ]

  return (
    <html lang="es">
      <body className={inter.className}>
        <main className="flex">
          <h2 className="w-full font-bold text-center">App de recetas</h2>
        </main>
        <NavMenu menuItems={menu} />
        <div>
        {children}
        </div>
      </body>
    </html>
  );
}
